### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by or0to** [nabil-ak/BTCFucker#4]
i would like to know how this script bf the pv key ?
and is there any chance you update it to work on inputted wordlist of passwords then the script generete a pv key for each password in the list then start bf all address he find ?

**Comment by nabil-ak** [comment]
It dosent work like this, this script just generates random private keys and then checks if the wallet contain bitcoins.

You dont need a wordlist and there is also no password, i dont even know what you mean with password.

Because every bitcoin wallet is just a pair of private and public key.

**Comment by or0to** [comment]
Ty for replay so the found wallet in the img is fake or you did test it and
worked ?

**Comment by nabil-ak** [comment]
No its fake the probability to find bitcoins is very very low. I created this project just for fun, its verly unlikely that you find a wallet that contain bitcoins.

**Comment by or0to** [comment]
So sad
Will could you create a new script that randomly brute force the prv key of
list address ?
