### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Lottmoorefundz** [nabil-ak/BTCFucker#5]
You will need to provide how many process you want to start!!!! What do I need to write please?

**Comment by nabil-ak** [comment]
You can write whatever you want but i would recommend to run the same amout of processes as cores you have.

**Comment by Lottmoorefundz** [comment]
I don’t understand what I need to write… i type 200 and it keep giving me
error

What do I need to write?

**Comment by nabil-ak** [comment]
Send me a screenshot of the error and 200 is way to much.

**Comment by Lottmoorefundz** [comment]
Ok I will do that. Thank you

**Comment by Lottmoorefundz** [comment]
This is what I keep getting and I don’t know what to do

**Comment by nabil-ak** [comment]
you didnt attached any pictures or code

**Comment by Lottmoorefundz** [comment]
I don’t really know how to do that, I’m new to this sorry
 Can you put me through please🙏

**Comment by Lottmoorefundz** [comment]
I sent you a picture of what I got, don’t you receive it..
Here you go
It says you need to provide how many process you want to start!!!
What is the answer to this ?

**Comment by nabil-ak** [comment]
start the script with `btcfucker.py 8` for example

**Comment by nabil-ak** [comment]
what error do you get?
